### ISSUE TITLE
App without audio when return result

### ISSUE THREAD

**Issue by JoseIgnacio92** [muhaos/react-native-speech-to-text-ios#11]
When it returns the result, something is in memory and the application is listening and that causes the phone to have no sound.

Sorry for my English

Thank you.

**Comment by martinblampied** [comment]
Fixed in https://github.com/muhaos/react-native-speech-to-text-ios/pull/12/commits/82adad8d23a43c277f51f98f8f0933f9a6656ba9

**Comment by JoseIgnacio92** [comment]
Thanks for the quick reply.
 I have not tried your solution yet, because I could solve it in the following way

```
- [audioSession setCategory:AVAudioSessionCategoryRecord error:&audioSessionError];
+ [audioSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker error:&audioSessionError];
```
