### ISSUE TITLE
Reset transcription on finish

### ISSUE THREAD

**Issue by zachgibson** [muhaos/react-native-speech-to-text-ios#14]
Is there a way to clear `formattedString`? I’m attempting to utter a phrase, capture `formattedString`, then repeat this with a new string, but without concatenating to the existing string.

**Comment by vvmusiienko** [comment]
There are two ways: finish current recognition task and start a new one. Or just keep track of the last content of formattedString and make substring from current formattedString minus previous formattedString content.

**Comment by zachgibson** [comment]
Cool, thanks @muhaos
