### ISSUE TITLE
Clear voice input and start a new SpeechToText

### ISSUE THREAD

**Issue by game2017** [muhaos/react-native-speech-to-text-ios#4]
I am trying to clear the previous value and then start a SpeechToText, I have this
`clearEventFunc() {
      SpeechToText.finishRecognition();
      SpeechToText.startRecognition('en-US');
}`
inside a function, how can I make the SpeechToText.finishRecognition() final?
Thank you

**Comment by zachgibson** [comment]
@game2017 did you ever figure this out?
