### ISSUE TITLE
AVSpeechSynthesizer does not speak after using SFSpeechRecognizer

### ISSUE THREAD

**Issue by pratomchaip** [muhaos/react-native-speech-to-text-ios#5]
When the `SFSpeechRecognizer` is turn on in `setupAndStartRecognizing()`,
it sets the audioSession category to _AVAudioSessionCategoryRecord_
`audioSession setCategory:AVAudioSessionCategoryRecord`

... but when the SpeechRecogniser is turned off in `teardown()`, the audioSession is not reset to play because it is left in Recording mode.

Possible solution is to reset the audioSession.setCategory to `AVAudioSessionCategoryPlayback` in the `teardown()` method.

I'm not an Objective-C/Swift developer so I can't do it myself.

... is that possible to implement in the next update?

**Comment by martinblampied** [comment]
Yes, the teardown is missing `self.audioSession = nil;`

**Comment by JoseIgnacio92** [comment]
It happens to me when the result returns. My application stops having audio because something is still not closed.

Any solution?

**Comment by martinblampied** [comment]
Fixed in https://github.com/muhaos/react-native-speech-to-text-ios/pull/12/commits/82adad8d23a43c277f51f98f8f0933f9a6656ba9
