### ISSUE TITLE
Hide alert boxes

### ISSUE THREAD

**Issue by martinblampied** [muhaos/react-native-speech-to-text-ios#8]
Is it possible to hide/disable the alert boxes for errors and warnings? I want to be able to handle these errors silently.

**Comment by vvmusiienko** [comment]
I can't find any internal alerts. All errors should be passed to JS side.
The only one alert that I can see is in JavaScript Example.
Can you please describe more details?

**Comment by martinblampied** [comment]
Talking about the alert boxes (see below). I want to be able to handle these messages myself.

![simulator screen shot 4 may 2017 09 41 09](https://cloud.githubusercontent.com/assets/3713820/25696139/f2ea8f4e-30ad-11e7-9d08-a70b2ee65c6a.png)

![simulator screen shot 4 may 2017 09 40 36](https://cloud.githubusercontent.com/assets/3713820/25696142/fac80e08-30ad-11e7-869d-24fde83fb5ae.png)

**Comment by martinblampied** [comment]
@muhaos Any ideas? 

It builds the errors in sendResult function then uses:
[self.bridge.eventDispatcher sendAppEventWithName:@"SpeechToText"
                                                 body:result];

Where do the AlertView's get built? I want to catch any errors in a console.log.

**Comment by martinblampied** [comment]
I'm an idiot.... it was the line
alert(JSON.stringify(result.error));
