### ISSUE TITLE
SpeechToText returning undefined

### ISSUE THREAD

**Issue by bob-zs** [muhaos/react-native-speech-to-text-ios#9]
Ran:

```js
import SpeechToText from 'react-native-speech-to-text-ios';
```

However, the console states that `SpeechToText` is undefined

**Comment by vvmusiienko** [comment]
Have you done `react-native link react-native-speech-to-text-ios` ?

**Comment by bob-zs** [comment]
@muhaos, yes, I have. And I figured out the issue. I had to run `npm install` and `pod install` multiple times, and I tried building with xcode, and the error `'RCTBridgeModule.h' file not found`

Basically, I was using a later version of npm and react-native, and the headers `<React/RCT*.h>` had to not have `React` in it. Changing all those files, the `SpeechToText` finally is not undefined.

The issue below helped.

https://github.com/oblador/react-native-vector-icons/issues/380
